Default: &defaults
  host: "127.0.0.1"
  port: 3000
  copyright: copyright Happiage project 2012-
  approot: "http://localhost:3000"
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://happiage.net"
  <<: *defaults
